# Generated by Django 5.2 on 2025-05-20 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investigacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delegado", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Patrulhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local", models.CharField(max_length=255)),
                ("horario", models.DateTimeField()),
                ("equipe", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vitima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.IntegerField()),
                ("endereco", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OcorrenciaCivil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ocorrencia", models.CharField(max_length=50)),
                ("data", models.DateTimeField()),
                ("descricao", models.TextField()),
                ("flagrante", models.BooleanField(default=False)),
                (
                    "investigacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seguranca_publica.investigacao",
                    ),
                ),
                (
                    "vitima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.vitima",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaMilitar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ocorrencia", models.CharField(max_length=50)),
                ("data", models.DateTimeField()),
                ("descricao", models.TextField()),
                ("tipo_patrulha", models.CharField(max_length=100)),
                (
                    "vitima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.vitima",
                    ),
                ),
                (
                    "patrulhamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seguranca_publica.patrulhamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
