# Generated by Django 5.2 on 2025-06-11 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sistema_justica", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investigacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delegado", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Patrulhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tipo_atendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instituicao_responsavel",
                    models.CharField(
                        choices=[
                            ("Policia Penal", "Policia Penal"),
                            ("Policia Civil", "Policia Civil"),
                            ("Policia Militar", "Policia Militar"),
                            (
                                "Centro de Atendimento Socioeducativo",
                                "Centro de Atendimento Socioeducativo",
                            ),
                            (
                                "Centro de Referência Especializado de Assistência Social",
                                "Centro de Referência Especializado de Assistência Social",
                            ),
                            (
                                "Centro de Atenção Psicossocial",
                                "Centro de Atenção Psicossocial",
                            ),
                        ],
                        default="Policia Penal",
                        max_length=100,
                        verbose_name="Nome da Instituição responsável",
                    ),
                ),
                (
                    "tematica",
                    models.CharField(
                        choices=[
                            ("Saúde", "Saúde"),
                            ("Educação", "Educação"),
                            ("Trabalho", "Trabalho"),
                            ("Assistência Social", "Assistência Social"),
                            ("Direitos Humanos", "Direitos Humanos"),
                            ("Segurança Pública", "Segurança Pública"),
                            ("Outros", "Outros"),
                        ],
                        default="Saúde",
                        max_length=100,
                        verbose_name="Temática",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OcorrenciaCivil",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "data",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "tipo_de_violencia",
                    models.CharField(
                        choices=[
                            ("Fisica", "Física"),
                            ("Psicologica", "Psicológica"),
                            ("Sexual", "Sexual"),
                            ("Patrimonial", "Patrimonial"),
                            ("Moral", "Moral"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Violência",
                    ),
                ),
                (
                    "grau_parentesco_agressor",
                    models.CharField(
                        choices=[
                            ("Pai", "Pai"),
                            ("Tio", "Tio"),
                            ("Conjuge", "Cônjuge"),
                            ("Filho", "Filho"),
                            ("Cunhado", "Cunhado"),
                            ("Padasto", "Padastro"),
                            ("Outros", "Outros"),
                        ],
                        default="Conjuge",
                        max_length=15,
                    ),
                ),
                (
                    "bairro_ocorrencia",
                    models.CharField(max_length=150, verbose_name="Bairro"),
                ),
                (
                    "status_MP",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SO", "Solicitada"),
                            ("NO", "Não Solicitada"),
                            ("AP", "Aprovada"),
                            ("RE", "Rejeitada"),
                            ("CA", "Cancelada"),
                            ("AT", "Ativa"),
                            ("EV", "Em Vigor"),
                        ],
                        default="SO",
                        max_length=2,
                        null=True,
                        verbose_name="Status da Medida Protetiva",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição da Ocorrência")),
                ("flagrante", models.BooleanField(default=False)),
                (
                    "agressor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_justica.agressor_dados",
                    ),
                ),
                (
                    "investigacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seguranca_publica.investigacao",
                    ),
                ),
                (
                    "vitima",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_justica.vitima_dados",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaMilitar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "data",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "tipo_de_violencia",
                    models.CharField(
                        choices=[
                            ("Fisica", "Física"),
                            ("Psicologica", "Psicológica"),
                            ("Sexual", "Sexual"),
                            ("Patrimonial", "Patrimonial"),
                            ("Moral", "Moral"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Violência",
                    ),
                ),
                (
                    "grau_parentesco_agressor",
                    models.CharField(
                        choices=[
                            ("Pai", "Pai"),
                            ("Tio", "Tio"),
                            ("Conjuge", "Cônjuge"),
                            ("Filho", "Filho"),
                            ("Cunhado", "Cunhado"),
                            ("Padasto", "Padastro"),
                            ("Outros", "Outros"),
                        ],
                        default="Conjuge",
                        max_length=15,
                    ),
                ),
                (
                    "bairro_ocorrencia",
                    models.CharField(max_length=150, verbose_name="Bairro"),
                ),
                (
                    "status_MP",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SO", "Solicitada"),
                            ("NO", "Não Solicitada"),
                            ("AP", "Aprovada"),
                            ("RE", "Rejeitada"),
                            ("CA", "Cancelada"),
                            ("AT", "Ativa"),
                            ("EV", "Em Vigor"),
                        ],
                        default="SO",
                        max_length=2,
                        null=True,
                        verbose_name="Status da Medida Protetiva",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição da Ocorrência")),
                ("vtr", models.CharField(max_length=20, verbose_name="VTR")),
                ("horario", models.DateTimeField(auto_now=True)),
                ("equipe", models.CharField(max_length=15, verbose_name="Equipe")),
                (
                    "tipo_patrulha",
                    models.CharField(
                        choices=[
                            ("EM", "Emergência 190"),
                            ("PM", "Policiamento Montado"),
                            ("TP", "Pelotão de Patrulhamento Tático"),
                            ("RP", "Radio Patrulha "),
                            ("PE", "Policiamento de Eventos"),
                            ("OA", "Operações de Aviação Policial"),
                            ("OE", "Operações Especiais"),
                            ("PC", "Policiamento com Cães"),
                            ("PB", "Policiamento ostensivo com bicicleta"),
                            ("PP", "Policiamento Ostensivo a Pé"),
                            ("PR", "Policiamento com Motocicleta"),
                            ("P2", "Agência de Inteligência"),
                            ("PS", "Policiamento em Praias"),
                            ("PT", "Policiamento Ostensivo de Trânsito"),
                        ],
                        default="RP",
                        max_length=4,
                        verbose_name="Patrulha",
                    ),
                ),
                (
                    "agressor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_justica.agressor_dados",
                    ),
                ),
                (
                    "vitima",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_justica.vitima_dados",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModeloPenal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "data_atendimento",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data do Atendimento",
                    ),
                ),
                (
                    "tempo_atendimento",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Tempo de Atendimento"
                    ),
                ),
                (
                    "setor_atendimento",
                    models.CharField(
                        choices=[
                            ("Assistente Social", "Assistente Social"),
                            ("Psicóloga", "Psicóloga"),
                            ("Enfermagem", "Enfermagem"),
                            ("Grupo refletivo", "Grupo refletivo"),
                            ("Outros", "Outros"),
                        ],
                        default="assistente social",
                        max_length=50,
                        verbose_name="Setor de Atendimento",
                    ),
                ),
                (
                    "avaliacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Avaliação do Atendimento"
                    ),
                ),
                ("teste", models.BooleanField(default=False, verbose_name="Teste")),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "atendimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo_atendimento",
                        to="seguranca_publica.tipo_atendimento",
                        verbose_name="Grupo de Atendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo Penal",
                "verbose_name_plural": "Modelos Penais",
                "ordering": ["-data_atendimento"],
                "permissions": [("Policia Penal", "Policia Penal")],
            },
        ),
    ]
