# Generated by Django 5.2 on 2025-05-23 22:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca_publica", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="tipo_atendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instituicao_responsavel",
                    models.CharField(
                        choices=[
                            ("Policia Penal", "Policia Penal"),
                            ("Policia Civil", "Policia Civil"),
                            ("Policia Militar", "Policia Militar"),
                            (
                                "Centro de Atendimento Socioeducativo",
                                "Centro de Atendimento Socioeducativo",
                            ),
                            (
                                "Centro de Referência Especializado de Assistência Social",
                                "Centro de Referência Especializado de Assistência Social",
                            ),
                            (
                                "Centro de Atenção Psicossocial",
                                "Centro de Atenção Psicossocial",
                            ),
                        ],
                        default="Policia Penal",
                        max_length=100,
                        verbose_name="Nome da Instituição responsável",
                    ),
                ),
                (
                    "tematica",
                    models.CharField(
                        choices=[
                            ("Saúde", "Saúde"),
                            ("Educação", "Educação"),
                            ("Trabalho", "Trabalho"),
                            ("Assistência Social", "Assistência Social"),
                            ("Direitos Humanos", "Direitos Humanos"),
                            ("Segurança Pública", "Segurança Pública"),
                            ("Outros", "Outros"),
                        ],
                        default="Saúde",
                        max_length=100,
                        verbose_name="Temática",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModeloPenal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "data_atendimento",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data do Atendimento",
                    ),
                ),
                (
                    "tempo_atendimento",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Tempo de Atendimento"
                    ),
                ),
                (
                    "setor_atendimento",
                    models.CharField(
                        choices=[
                            ("Assistente Social", "Assistente Social"),
                            ("Psicóloga", "Psicóloga"),
                            ("Enfermagem", "Enfermagem"),
                            ("Grupo refletivo", "Grupo refletivo"),
                            ("Outros", "Outros"),
                        ],
                        default="assistente social",
                        max_length=50,
                        verbose_name="Setor de Atendimento",
                    ),
                ),
                (
                    "avaliacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Avaliação do Atendimento"
                    ),
                ),
                ("teste", models.BooleanField(default=False, verbose_name="Teste")),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "atendimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo_atendimento",
                        to="seguranca_publica.tipo_atendimento",
                        verbose_name="Grupo de Atendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo Penal",
                "verbose_name_plural": "Modelos Penais",
                "ordering": ["-data_atendimento"],
                "permissions": [("Policia Penal", "Policia Penal")],
            },
        ),
    ]
