# Generated by Django 5.2.4 on 2025-08-16 21:51

import MAIN.cadastros_padrao
import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguranca_publica', '0001_initial'),
        ('sistema_justica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelopenal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='ocorrenciacivil',
            name='Estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='ocorrenciacivil',
            name='agressor',
            field=models.ForeignKey(blank=True, default=MAIN.cadastros_padrao.agressor_padrao, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sistema_justica.agressor_dados'),
        ),
        migrations.AddField(
            model_name='ocorrenciacivil',
            name='comarca_competente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.comarcaspoderjudiciario', verbose_name='Comarca'),
        ),
        migrations.AddField(
            model_name='ocorrenciacivil',
            name='investigacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seguranca_publica.investigacao'),
        ),
        migrations.AddField(
            model_name='ocorrenciacivil',
            name='municipio_ocorrencia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='Estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='ocorrenciacivil',
            name='vitima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.vitima_dados'),
        ),
        migrations.AddField(
            model_name='ocorrenciamilitar',
            name='Estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='ocorrenciamilitar',
            name='agressor',
            field=models.ForeignKey(blank=True, default=MAIN.cadastros_padrao.agressor_padrao, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sistema_justica.agressor_dados'),
        ),
        migrations.AddField(
            model_name='ocorrenciamilitar',
            name='comarca_competente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.comarcaspoderjudiciario', verbose_name='Comarca'),
        ),
        migrations.AddField(
            model_name='ocorrenciamilitar',
            name='municipio_ocorrencia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='Estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='ocorrenciamilitar',
            name='vitima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.vitima_dados'),
        ),
        migrations.AddField(
            model_name='modelopenal',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_atendimento', to='seguranca_publica.tipo_atendimento', verbose_name='Grupo de Atendimento'),
        ),
    ]
