# Generated by Django 5.2 on 2025-05-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca_publica", "0002_tipo_atendimento_modelopenal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrenciacivil",
            name="descricao",
            field=models.TextField(verbose_name="Descrição da Ocorrência"),
        ),
        migrations.AlterField(
            model_name="ocorrenciamilitar",
            name="descricao",
            field=models.TextField(verbose_name="Descrição da Ocorrência"),
        ),
    ]
