# Generated by Django 5.2.4 on 2025-09-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca_publica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciacivil',
            name='grau_parentesco_agressor',
            field=models.CharField(choices=[('Pai', 'Pai'), ('Tio', 'Tio'), ('Conjuge', 'Cônjuge'), ('Filho', 'Filho'), ('Cunhado', 'Cunhado'), ('Padasto', 'Padastro'), ('Primo', 'Primo/Prima'), ('Irmao', 'Irmão'), ('ex-Conjuge', 'Ex-Cônjuge'), ('amigo', 'Amigo da família'), ('Outros', 'Outros')], default='Conjuge', max_length=15),
        ),
        migrations.AlterField(
            model_name='ocorrenciamilitar',
            name='grau_parentesco_agressor',
            field=models.CharField(choices=[('Pai', 'Pai'), ('Tio', 'Tio'), ('Conjuge', 'Cônjuge'), ('Filho', 'Filho'), ('Cunhado', 'Cunhado'), ('Padasto', 'Padastro'), ('Primo', 'Primo/Prima'), ('Irmao', 'Irmão'), ('ex-Conjuge', 'Ex-Cônjuge'), ('amigo', 'Amigo da família'), ('Outros', 'Outros')], default='Conjuge', max_length=15),
        ),
    ]
