# Generated by Django 5.2.6 on 2025-12-16 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img_home/', verbose_name='Imagem')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Vídeo')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicar na página Inicial?')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('link', models.URLField(blank=True, max_length=150, null=True, verbose_name='Link')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('secao', models.CharField(choices=[('seguranca_publica', 'Segurança Pública'), ('sistema_justica', 'Sistema de Justiça'), ('municipio', 'Município'), ('leis', 'Leis'), ('noticias', 'Notícias'), ('sobre', 'Sobre')], default='noticias', max_length=50, verbose_name='Seção')),
            ],
            options={
                'verbose_name': 'Conteúdo da Página Inicial',
                'verbose_name_plural': 'Conteúdos da Página Inicial',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
