# Generated by Django 5.2 on 2025-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vitima",
            fields=[
                (
                    "id_vitima",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID da Vítima"
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("endereco", models.TextField()),
                ("telefone", models.CharField(max_length=15)),
                ("qtd_filhos", models.IntegerField(default=0)),
            ],
        ),
    ]
