# Generated by Django 5.2.4 on 2025-09-01 18:28

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comprovante_vinculo',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/comprovantes/%Y/%m/', validators=[usuarios.models.CustomUser.validate_pdf_file], verbose_name='Comprovante de Vínculo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Poder Judiciário', 'Poder Judiciário'), ('Ministério Público', 'Ministério Público'), ('Defensoria Pública', 'Defensoria Pública'), ('Polícia Civil', 'Polícia Civil'), ('Polícia Militar', 'Polícia Militar'), ('Polícia Penal', 'Polícia Penal'), ('Polícia Científica', 'Polícia Científica'), ('CAPS', 'CAPS'), ('Conselho Tutelar', 'Conselho Tutelar'), ('CRAS', 'CRAS'), ('CREAS', 'CREAS'), ('Secretaria da Saúde', 'Secretaria da Saúde')], max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Prefiro não informar')], max_length=10, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/%Y/%m/', verbose_name='Foto do Perfil'),
        ),
    ]
