# Generated by Django 5.2 on 2025-05-24 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="agressor_dados",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do agressor",
                        max_length=250,
                        unique=True,
                        verbose_name="Nome Completo do Agressor",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Formato: 000.000.000-00",
                        max_length=14,
                        verbose_name="CPF do Agressor",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        help_text="Data de nascimento do agressor",
                        unique=True,
                        verbose_name="Data de Nascimento do Agressor",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        help_text="Escolha o sexo do agressor",
                        max_length=1,
                        verbose_name="Sexo do Agressor",
                    ),
                ),
                (
                    "idade",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        choices=[
                            ("BR", "Brasileiro"),
                            ("PT", "Português"),
                            ("ES", "Espanhol"),
                            ("EN", "Inglês"),
                            ("FR", "Francês"),
                            ("IT", "Italiano"),
                            ("DE", "Alemão"),
                            ("CN", "Chinês"),
                            ("JP", "Japonês"),
                            ("IN", "Indiano"),
                        ],
                        default="BR",
                        help_text="Escolha a nacionalidade do agressor",
                        max_length=2,
                        verbose_name="Nacionalidade do Agressor",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        max_length=255, verbose_name="Endereço do Agressor"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Formato: (DDD) XXXXX-XXXX",
                        max_length=15,
                        verbose_name="Telefone do Agressor",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email do Agressor"
                    ),
                ),
                (
                    "escolaridade",
                    models.CharField(
                        choices=[
                            ("AN", "Analfabeto"),
                            ("EF", "Ensino Fundamental"),
                            ("EM", "Ensino Médio"),
                            ("SU", "Superior Incompleto"),
                            ("SS", "Superior Completo"),
                            ("PO", "Pós-Graduação"),
                        ],
                        default="EF",
                        help_text="Escolha a escolaridade do agressor",
                        max_length=2,
                        verbose_name="Escolaridade do Agressor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vitima_dados",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo da vítima",
                        max_length=250,
                        unique=True,
                        verbose_name="Nome Completo da Vítima",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Formato: 000.000.000-00",
                        max_length=14,
                        verbose_name="CPF da Vítima",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        help_text="Data de nascimento da vítima",
                        unique=True,
                        verbose_name="Data de Nascimento da Vítima",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        help_text="Escolha o sexo da vítima",
                        max_length=1,
                        verbose_name="Sexo da Vítima",
                    ),
                ),
                (
                    "idade",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        choices=[
                            ("BR", "Brasileiro"),
                            ("PT", "Português"),
                            ("ES", "Espanhol"),
                            ("EN", "Inglês"),
                            ("FR", "Francês"),
                            ("IT", "Italiano"),
                            ("DE", "Alemão"),
                            ("CN", "Chinês"),
                            ("JP", "Japonês"),
                            ("IN", "Indiano"),
                        ],
                        default="BR",
                        help_text="Escolha a nacionalidade da vítima",
                        max_length=2,
                        verbose_name="Nacionalidade da Vítima",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(max_length=255, verbose_name="Endereço da Vítima"),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Formato: (DDD) XXXXX-XXXX",
                        max_length=15,
                        verbose_name="Telefone da Vítima",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email da Vítima"
                    ),
                ),
                (
                    "escolaridade",
                    models.CharField(
                        choices=[
                            ("AN", "Analfabeto"),
                            ("EF", "Ensino Fundamental"),
                            ("EM", "Ensino Médio"),
                            ("SU", "Superior Incompleto"),
                            ("SS", "Superior Completo"),
                            ("PO", "Pós-Graduação"),
                        ],
                        default="EF",
                        help_text="Escolha a escolaridade da vítima",
                        max_length=2,
                        verbose_name="Escolaridade da Vítima",
                    ),
                ),
                (
                    "nome_agressor",
                    models.CharField(
                        help_text="Nome do agressor, se conhecido. Caso contrário, deixe em branco.",
                        max_length=250,
                        verbose_name="agressor_dados.nome",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        help_text="Usuário Responsável pelos dados da vítima",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados da Vítima",
                "verbose_name_plural": "Dados das Vítimas",
            },
        ),
    ]
