# Generated by Django 5.2 on 2025-05-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vitima_dados",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo da vítima",
                        max_length=250,
                        unique=True,
                        verbose_name="Nome Completo da Vítima",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Formato: 000.000.000-00",
                        max_length=14,
                        verbose_name="CPF da Vítima",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        help_text="Data de nascimento da vítima",
                        unique=True,
                        verbose_name="Data de Nascimento da Vítima",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        help_text="Escolha o sexo da vítima",
                        max_length=1,
                        verbose_name="Sexo da Vítima",
                    ),
                ),
                (
                    "idade",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        choices=[
                            ("BR", "Brasileiro"),
                            ("PT", "Português"),
                            ("ES", "Espanhol"),
                            ("EN", "Inglês"),
                            ("FR", "Francês"),
                            ("IT", "Italiano"),
                            ("DE", "Alemão"),
                            ("CN", "Chinês"),
                            ("JP", "Japonês"),
                            ("IN", "Indiano"),
                        ],
                        default="BR",
                        help_text="Escolha a nacionalidade da vítima",
                        max_length=2,
                        verbose_name="Nacionalidade da Vítima",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(max_length=255, verbose_name="Endereço da Vítima"),
                ),
                (
                    "telefone",
                    models.CharField(max_length=15, verbose_name="Telefone da Vítima"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email da Vítima"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
