# Generated by Django 5.2.4 on 2025-08-16 21:51

import datetime
import django.db.models.deletion
import sistema_justica.models.defensoria_publica
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, null=True, unique=True, verbose_name='Sigla do Estado')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome do Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Agressor_dados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Agressor')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome*')),
                ('cpf', models.CharField(help_text='000.000.000-00', max_length=14, unique=True, verbose_name='CPF*')),
                ('nome_social', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Social')),
                ('nome_do_pai', models.CharField(max_length=250, null=True, verbose_name='Pai*')),
                ('nome_da_mae', models.CharField(max_length=250, null=True, verbose_name='Mãe*')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento*')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1, verbose_name='Sexo*')),
                ('ativa', models.BooleanField(default=True)),
                ('etnia', models.CharField(choices=[('BR', 'Branca'), ('PR', 'Preta'), ('PA', 'Parda'), ('AM', 'Amarela'), ('IN', 'Indígena')], max_length=2, verbose_name='Etnia*')),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('A', 'Amasiado(a)'), ('U', 'União Estável'), ('O', 'Outros')], default='S', max_length=2, null=True, verbose_name='Estado Civil*')),
                ('idade', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone*')),
                ('nacionalidade', models.CharField(choices=[('BR', 'Brasileiro'), ('PT', 'Português'), ('ES', 'Espanhol'), ('EN', 'Inglês'), ('FR', 'Francês'), ('IT', 'Italiano'), ('DE', 'Alemão'), ('CN', 'Chinês'), ('JP', 'Japonês'), ('IN', 'Indiano')], default='BR', max_length=2, verbose_name='Nacionalidade*')),
                ('bairro', models.CharField(max_length=100, null=True, verbose_name='Bairro*')),
                ('endereco', models.CharField(max_length=255, null=True, verbose_name='Endereço*')),
                ('endereco_numero', models.IntegerField(null=True, verbose_name='Nº*')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('escolaridade', models.CharField(choices=[('AN', 'Não Alfabetizado'), ('FI', 'Ensino Fundamental Incompleto'), ('FC', 'Ensino Fundamental Completo'), ('EI', 'Ensino Médio Incompleto'), ('EC', 'Ensino Médio Completo'), ('SU', 'Superior Incompleto'), ('SS', 'Superior Completo'), ('PO', 'Pós-Graduação')], default='EF', max_length=2, verbose_name='Escolaridade*')),
                ('classeEconomica', models.CharField(choices=[('SR', 'Sem Renda'), ('AB', 'Abaixo de R$1.518,00'), ('BA', 'De R$1.518,01 a R$3.636,00'), ('BC', 'De R$3.636,01 a R$7.017,63'), ('BD', 'De R$7.017,64 a R$28.239,99'), ('AC', 'Acima de R$28.240,00')], max_length=2, verbose_name='Renda Mensal*')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão*')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_justica.estado', verbose_name='Estado*')),
            ],
            options={
                'verbose_name': 'Dados do Agressor',
                'verbose_name_plural': 'Dados dos Agressores',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Município')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema_justica.estado', verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Filhos_dados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Filho')),
                ('nome', models.CharField(max_length=250, null=True, verbose_name='Nome Completo*')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento*')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo*')),
                ('idade', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('cpf', models.CharField(blank=True, help_text='000.000.000-00', max_length=14, null=True, verbose_name='CPF*')),
                ('nacionalidade', models.CharField(choices=[('BR', 'Brasileiro'), ('PT', 'Português'), ('ES', 'Espanhol'), ('EN', 'Inglês'), ('FR', 'Francês'), ('IT', 'Italiano'), ('DE', 'Alemão'), ('CN', 'Chinês'), ('JP', 'Japonês'), ('IN', 'Indiano')], default='BR', max_length=2, verbose_name='Nacionalidade*')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_justica.estado', verbose_name='Estado*')),
                ('nome_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_justica.agressor_dados', verbose_name='Pai*')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.municipio', verbose_name='Município*')),
            ],
            options={
                'verbose_name': 'Dados dos Filhos',
                'verbose_name_plural': 'Dados dos Filhos',
            },
        ),
        migrations.CreateModel(
            name='ComarcasPoderJudiciario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Comarca')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.estado', verbose_name='Estado')),
                ('municipios_abrangentes', smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', horizontal=True, related_name='comarcas_abrangentes', to='sistema_justica.municipio', verbose_name='Municípios Abrangentes')),
            ],
            options={
                'verbose_name': 'Comarca do Poder Judiciário',
                'verbose_name_plural': 'Comarcas do Poder Judiciário',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='agressor_dados',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.municipio', verbose_name='Município*'),
        ),
        migrations.CreateModel(
            name='Vitima_dados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Vítima')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome Completo*')),
                ('cpf', models.CharField(help_text='000.000.000-00', max_length=14, verbose_name='CPF*')),
                ('nome_social', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Social')),
                ('nome_do_pai', models.CharField(max_length=250, verbose_name='Pai*')),
                ('nome_da_mae', models.CharField(max_length=250, verbose_name='Mãe*')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento*')),
                ('ativa', models.BooleanField(default=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='F', max_length=1, verbose_name='Sexo*')),
                ('etnia', models.CharField(choices=[('BR', 'Branca'), ('PR', 'Preta'), ('PA', 'Parda'), ('AM', 'Amarela'), ('IN', 'Indígena')], max_length=2, verbose_name='Etnia*')),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('A', 'Amasiado(a)'), ('U', 'União Estável'), ('O', 'Outros')], default='S', max_length=2, null=True, verbose_name='Estado Civil*')),
                ('idade', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone*')),
                ('nacionalidade', models.CharField(choices=[('BR', 'Brasileiro'), ('PT', 'Português'), ('ES', 'Espanhol'), ('EN', 'Inglês'), ('FR', 'Francês'), ('IT', 'Italiano'), ('DE', 'Alemão'), ('CN', 'Chinês'), ('JP', 'Japonês'), ('IN', 'Indiano')], default='BR', max_length=2, verbose_name='Nacionalidade*')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro*')),
                ('endereco_rua', models.CharField(max_length=255, null=True, verbose_name='Endereço*')),
                ('endereco_numero', models.IntegerField(blank=True, null=True, verbose_name='Nº*')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('escolaridade', models.CharField(choices=[('AN', 'Não Alfabetizado'), ('FI', 'Ensino Fundamental Incompleto'), ('FC', 'Ensino Fundamental Completo'), ('EI', 'Ensino Médio Incompleto'), ('EC', 'Ensino Médio Completo'), ('SU', 'Superior Incompleto'), ('SS', 'Superior Completo'), ('PO', 'Pós-Graduação')], default='EF', max_length=2, verbose_name='Escolaridade*')),
                ('classeEconomica', models.CharField(choices=[('SR', 'Sem Renda'), ('AB', 'Abaixo de R$1.518,00'), ('BA', 'De R$1.518,01 a R$3.636,00'), ('BC', 'De R$3.636,01 a R$7.017,63'), ('BD', 'De R$7.017,64 a R$28.239,99'), ('AC', 'Acima de R$28.240,00')], max_length=2, verbose_name='Classe Econômica*')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão*')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_justica.estado', verbose_name='Estado*')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.municipio', verbose_name='Município*')),
            ],
            options={
                'verbose_name': 'Dados da Vítima',
                'verbose_name_plural': 'Dados das Vítimas',
            },
        ),
        migrations.CreateModel(
            name='FormularioMedidaProtetiva',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Solicitação')),
                ('periodo_mp', models.DateField(default=sistema_justica.models.defensoria_publica.default_periodo_mp, verbose_name='Período da Medida Protetiva')),
                ('solicitada_mpu', models.BooleanField(default=True, verbose_name='Medida Protetiva de Urgência')),
                ('tipo_de_violencia', models.CharField(choices=[('Fisica', 'Física'), ('Psicologica', 'Psicológica'), ('Sexual', 'Sexual'), ('Patrimonial', 'Patrimonial'), ('Moral', 'Moral')], max_length=50, verbose_name='Tipo de Violência')),
                ('bairro_mp', models.CharField(max_length=100, null=True, verbose_name='Bairro:')),
                ('grau_parentesco_agressor', models.CharField(choices=[('Pai', 'Pai'), ('Tio', 'Tio'), ('Conjuge', 'Cônjuge'), ('Filho', 'Filho'), ('Cunhado', 'Cunhado'), ('Padasto', 'Padastro'), ('Primo', 'Primo/Prima'), ('Irmao', 'Irmão'), ('Outros', 'Outros')], default='Conjuge', max_length=15, verbose_name='Grau de Parentesco com o Agressor')),
                ('agressor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.agressor_dados', verbose_name='Agressor')),
                ('comarca_competente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.comarcaspoderjudiciario', verbose_name='Comarca Competente')),
                ('filhos', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='agressor', chained_model_field='agressor', null=True, to='sistema_justica.filhos_dados', verbose_name='Filhos')),
                ('municipio_mp', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='comarca_competente', chained_model_field='comarcas_abrangentes', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.municipio', verbose_name='Município do Fato')),
                ('vitima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_justica.vitima_dados', verbose_name='Vitima')),
            ],
            options={
                'verbose_name': 'Formulario MP',
                'verbose_name_plural': 'Formularios MP',
                'ordering': ['data_solicitacao'],
            },
        ),
        migrations.AddField(
            model_name='filhos_dados',
            name='nome_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_justica.vitima_dados', verbose_name='Mãe*'),
        ),
    ]
