# Generated by Django 5.2.4 on 2025-09-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_justica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='afastamento_fami_ami',
            field=models.BooleanField(default=False, verbose_name='49. Afastamento de familiares ou amigos/as?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='afastamento_trabalho',
            field=models.BooleanField(default=False, verbose_name='48. Afastamento do trabalho ou estudos?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='agia_agre_filhos_punir',
            field=models.BooleanField(default=False, verbose_name='38. Agia com agressividade com os filhos como forma de puni-la?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='alteracao_apetite',
            field=models.BooleanField(default=False, verbose_name='53. Teve alterações do apetite com aumento ou perda de peso?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='amante_paquera',
            field=models.BooleanField(default=False, verbose_name='28. Explodia por ciúmes, dizia que você tinha amantes ou estava paquerando?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='ameaca_filho_desiste_proc',
            field=models.BooleanField(default=False, verbose_name='37. Ameaçava seus filhos para você desistir de algum processo?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='ameaca_se_matar',
            field=models.BooleanField(default=False, verbose_name='16. Ameaçava que ia se matar ou matar seus filhos quando você tentava terminar a relação?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='apelidos_tristes',
            field=models.BooleanField(default=False, verbose_name='11. Criava apelidos para você, que a deixavam constrangida ou triste?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='boa_dona_casa',
            field=models.BooleanField(default=False, verbose_name='15. Afirmava que você era uma boa "dona de casa", "boa mãe" e "esposa" para justificar o comportamento abusivo?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='bravo_conversa_homem',
            field=models.BooleanField(default=False, verbose_name='22. Ficava aborrecido ou bravo se você conversava com homens que não eram da família?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='ciumes_atencao_proximidade',
            field=models.BooleanField(default=False, verbose_name='26. Tinha ciúmes se alguma pessoa lhe desse atenção ou se aproximasse de você?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='comentario_situacao',
            field=models.TextField(blank=True, null=True, verbose_name='Você gostaria de contar detalhes ou outra situação de constrangimento?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='constante_estado_alerta',
            field=models.BooleanField(default=False, verbose_name='46. Constante estado de alerta (atenção e medo)?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='constrangia_frente_outras_pessoas',
            field=models.BooleanField(default=False, verbose_name='3. Constrangia você na frente de outras pessoas?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='contar_segredo',
            field=models.BooleanField(default=False, verbose_name='32. Ameaçava contar seus segredos pessoais ou divulgar fotos suas para outras pessoas?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='controlava_distancia',
            field=models.BooleanField(default=False, verbose_name='24. Controlava você por mensagens, ligações ou de outro modo?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='coracao_ace_sexo_oposto',
            field=models.BooleanField(default=False, verbose_name='56. Coração acelerado (taquicardia) ou falta de ar quando alguém do sexo oposto chega próximo?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='critica_aparencia',
            field=models.BooleanField(default=False, verbose_name='1. Criticava sua aparência (corpo, cabelo, roupas)?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='culpava_ruim_voce',
            field=models.BooleanField(default=False, verbose_name='13. Culpava você por tudo de ruim que acontecia (desempego, dívidas e outros)?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='deixar_sem_nada',
            field=models.BooleanField(default=False, verbose_name='33.   Dizia que, se o deixasse, entraria com vários processos e ficaria sem nada?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='deixava_remedio_filhos',
            field=models.BooleanField(default=False, verbose_name='39. Deixava de dar remédios para filhos doentes ou que necessitavam de cuidados especiais como forma de puni-la?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='deixou_relacionar_afetiva_sexu',
            field=models.BooleanField(default=False, verbose_name='50. Deixou de se relacionar sexualmente ou afetivamente com outras pessoas (por medo ou desconfiança)?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='deixou_relacionar_afetiva_sexu_mesAgressor',
            field=models.BooleanField(default=False, verbose_name='51. Deixou de se relacionar com pessoas do mesmo sexo do agressor (por medo ou desconfiança)?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='desenvolveu_fobia',
            field=models.BooleanField(default=False, verbose_name='52. Desenvolveu alguma fobia ou medo específico (altura, animais, pessoas, sangue)?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='destruia_moveis_casa',
            field=models.BooleanField(default=False, verbose_name='30. Destruía móveis ou utensílios da casa?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='detalhes_coisas',
            field=models.TextField(blank=True, null=True, verbose_name='Você gostaria de contar mais detalhes ou alguma situação específica?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='detalhes_medo',
            field=models.TextField(blank=True, null=True, verbose_name='Você gostaria de contar mais detalhes ou outra situação que lhe causava medo?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='dificula_contato_familia',
            field=models.BooleanField(default=False, verbose_name='18. Dificultava seu contato com familiares?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='dificuldade_fazer_atividades',
            field=models.BooleanField(default=False, verbose_name='47. Dificuldade para realizar as atividades do dia a dia, que antes você fazia normalmente?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='doente_frequente',
            field=models.BooleanField(default=False, verbose_name='54. Passou a ficar doente com frequência (dores crônicas, lesões ou doenças de pele, alterações hormonais, pressão alta, queda de cabelo, alterações da visão, ou outro sintoma físico)?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='escolhia_amizade',
            field=models.BooleanField(default=False, verbose_name='23. Escolhia suas amizades?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='escondia_coisas_pessoais',
            field=models.BooleanField(default=False, verbose_name='29. Destruía ou escondia suas coisas pessoais?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='estado_desanimo',
            field=models.BooleanField(default=False, verbose_name='57. Estado de desânimo, apatia ou indiferença em ambientes de lazer?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='evita_pessoas_locais',
            field=models.BooleanField(default=False, verbose_name='42. Passou a evitar pessoas ou lugares que relembram os fatos?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='exibia_armas',
            field=models.BooleanField(default=False, verbose_name='34. Exibia armas de fogo, facas ou objetos como forma de intimação?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='fazer_nao_gosta',
            field=models.BooleanField(default=False, verbose_name='5. Constrangia você a fazer coisas que não gostava?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='filhos_riscos',
            field=models.BooleanField(default=False, verbose_name='40. Colocava seus filhos em situações de riscos como forma de punila?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='frequencia_condutas',
            field=models.CharField(blank=True, choices=[('no_descreveu', 'Não Descreveu'), ('pou_vezes', 'Poucas Vezes'), ('as_vezes', 'Muitas Vezes'), ('sempre', 'Sempre')], max_length=15, null=True, verbose_name='As condutas de constrangimento, humilhação, manipulação, de isolamento ou ameaçadoras que você descreveu aconteciam com que frequência'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='gritava_qualquer_coisa',
            field=models.BooleanField(default=False, verbose_name='27. Gritava ou explodia por qualquer coisa?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='guarda_filhos',
            field=models.BooleanField(default=False, verbose_name='36. Ameaçava pedir a guarda dos filhos?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='humiliava_frente_filhos',
            field=models.BooleanField(default=False, verbose_name='8. Humilhava você na frente de seus filhos?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='info_situa_isola',
            field=models.TextField(blank=True, null=True, verbose_name='Você gostaria de contar mais detalhes ou outra situação de isolamento?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='insegurancas_capza',
            field=models.BooleanField(default=False, verbose_name='14. Usava seus medos e inseguranças dizendo que você não era capaz?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='invertia_fatos',
            field=models.BooleanField(default=False, verbose_name='17. Escondia, coisas invertia fatos e dizia que você estava louca?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='irritabilidade_constante',
            field=models.BooleanField(default=False, verbose_name='60. Passou a ter irritabilidade constante?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='maltratava_animal_estimacao',
            field=models.BooleanField(default=False, verbose_name='31. Maltratava ou ameaçava seus animais de estimação?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='manipula_IA',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='manipulado_IA_BOOL',
            field=models.BooleanField(default=False, verbose_name='35. Para alguma das condutas anteriores, foi utilizada Inteligência Artificial (como programas ou aplicativos) ou outro recurso tecnológico para alterar imagem pessoal ou voz (fotos ou vídeos montados com sua imagem ou voz)?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='medo_sozinha_casa',
            field=models.BooleanField(default=False, verbose_name='43. Medo de ficar sozinha em casa ou sair desacompanhada?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='obrigava_pedir_desculpas',
            field=models.BooleanField(default=False, verbose_name='4. Obrigava você a pedir desculpas, mesmo quando não era sua culpa?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='observacoes_profissional',
            field=models.TextField(blank=True, null=True, verbose_name='Observações profissionais'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='olha_mundo_perigoso',
            field=models.BooleanField(default=False, verbose_name='59. Passou a ver o mundo como um lugar perigoso e não consegue confiar nas pessoas?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='outras_condutas_vicaria',
            field=models.TextField(blank=True, null=True, verbose_name='Outras situações'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='perdeu_vontade_viver_suicida',
            field=models.BooleanField(default=False, verbose_name='61. Perdeu a vontade de viver ou teve ideação suicida?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='perdia_cabeca_culpava',
            field=models.BooleanField(default=False, verbose_name='12. Alegava que "perdia a cabeça" e culpava você?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='pesadelo_dormir',
            field=models.BooleanField(default=False, verbose_name='44. Pesadelos ou dificuldade para dormir?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='piadas_familia',
            field=models.BooleanField(default=False, verbose_name='9. Fazia piadas sobre ou você sua familia?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='proibia_make_roupas',
            field=models.BooleanField(default=False, verbose_name='2. Proibia você de usar roupas ou maquiagem?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='reclama_saia_sozinha',
            field=models.BooleanField(default=False, verbose_name='20. Reclamava quando você saía sozinha?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='reclama_sozinha_estudar_trabalhar',
            field=models.BooleanField(default=False, verbose_name='21. Reclamava quando você saía para estudar ou trabalhar?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='recusava_pagar_pensao',
            field=models.BooleanField(default=False, verbose_name='41. Recusava-se a pegar pensão para os filhos como forma de chantagem ou punição?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='relato_constrangida',
            field=models.TextField(blank=True, null=True, verbose_name='Você gostaria de contar mais detalhes ou mencionar alguma situação de humilhação ou ridicularização?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='ridicularizava_sozinha',
            field=models.BooleanField(default=False, verbose_name='6. Ofendia, envergonhava ou ridicularizava você quando estavam sozinhos?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='ridicularizava_terceiros',
            field=models.BooleanField(default=False, verbose_name='7. Ofendia, envergonhava ou ridicularizava você quando estavam na frente de outras pessoas?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='senhas_redes_sociais',
            field=models.BooleanField(default=False, verbose_name='25. Exigia que você lhe desse suas senhas em redes sociais?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='sentir_incapaz',
            field=models.BooleanField(default=False, verbose_name='58. Passou a se sentir incapaz, fracassada ou sem valor?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='sintomas_persistem',
            field=models.TextField(blank=True, null=True, verbose_name='Os sintomas ainda persistem? Descreva, apontando se há necessidade de atendimento ou encaminhamento da vítima.'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='telefone_familia_viva_voz',
            field=models.BooleanField(default=False, verbose_name='19. Quando seus familiares ligavam, obrigava você a colocar em viva voz?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='tremores_lembras',
            field=models.BooleanField(default=False, verbose_name='55. Tremores ao relembrar dos fatos?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='tristeza_profunda',
            field=models.BooleanField(default=False, verbose_name='45. Tristeza profunda ou crises de choro?'),
        ),
        migrations.AddField(
            model_name='formulariomedidaprotetiva',
            name='xingava_louca_burra',
            field=models.BooleanField(default=False, verbose_name='10. Xingava você de louca, burra, incapaz ou que não fazia nada direito?'),
        ),
        migrations.AlterField(
            model_name='formulariomedidaprotetiva',
            name='grau_parentesco_agressor',
            field=models.CharField(choices=[('Pai', 'Pai'), ('Tio', 'Tio'), ('Conjuge', 'Cônjuge'), ('Filho', 'Filho'), ('Cunhado', 'Cunhado'), ('Padasto', 'Padastro'), ('Primo', 'Primo/Prima'), ('Irmao', 'Irmão'), ('ex-Conjuge', 'Ex-Cônjuge'), ('amigo', 'Amigo da família'), ('Outros', 'Outros')], default='Conjuge', max_length=15, verbose_name='Grau de Parentesco com o Agressor'),
        ),
    ]
